version: "3"
services:
  web:
    restart: always
    build: .
    ports:
      - "80:8080"
#    volumes:
#     - ./web:/code # modified here to take into account the new app path
    environment:
      - NODE_ENV=production