version: "3"
services:
  node:
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

  nginx:
    build: ./nginx
    links:
      - node:node
    ports:
      - "80:80"
      - "443:443"
    volumes:
     - /usr/share/nginx/html:/usr/share/nginx/html
     - /etc/letsencrypt:/etc/letsencrypt
     - /etc/ssl:/etc/ssl
    environment:
      - DOMAIN_NAME=samcackett.com