version: "3"
services:
  node:
    restart: always
    build: .
    ports:
      - "8080:8080"
#    volumes:
#     - ./web:/code # modified here to take into account the new app path
    environment:
      - NODE_ENV=production

  nginx:
    build: ./nginx
    links:
      - node:node
    ports:
      - "80:80"
      - "443:443"
#    volumes:
#      - /etc/nginx/psw:/etc/nginx/psw
#      - /etc/nginx/ssl:/etc/nginx/ssl
    environment:
      - DOMAIN_NAME=samcackett.com